apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hashbangctl
resources:
  - resources.yaml
commonLabels:
  app.kubernetes.io/name: hashbangctl
images:
  - name: hashbang/hashbangctl
