apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashbangctl
spec:
  template:
    spec:
      containers:
        - name: hashbangctl
          image: hashbang/hashbangctl
          env:
            - name: API_URL
              value: https://userdb.hashbang.sh/v1
            - name: API_TOKEN
              value: eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYXBpLXVzZXItY3JlYXRlIn0.iOcRzRAjPsT9DOhu5OSeRuQ38D3KL5NppsfyuZYiDeI
            - name: HOST_KEY_ED25519
              value: LS0tLSirstsr1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNESzlaUjcrcVhGbnhYb21PaWY1cERoQ01TQVhPYlU5eTZGdlJOSWFJdi92UUFBQUppbHkxYnVwY3RXCjdnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDREs5WlI3K3FYRm54WG9tT2lmNXBEaENNU0FYT2JVOXk2RnZSTklhSXYvdlEKQUFBRUEvVng5Q0dxMzg3R2ZnVmFHREtROGMzK09HWWp6WU9HLzVkODI0RVNVQitzcjFsSHY2cGNXZkZlaVk2Si9ta09FSQp4SUJjNXRUM0xvVzlFMGhvaS8rOUFBQUFEMnh5ZG1samEwQndaWEp6YjI1aGJBRUNBd1FGQmc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
          ports:
            - containerPort: 2222
              name: ssh
---
apiVersion: v1
kind: Service
metadata:
  name: hashbangctl
spec:
  ports:
    - name: ssh
      targetPort: ssh
      nodePort: 30022
      port: 22
  type: NodePort
